steps:
steps:
  - label: "{{matrix}} build"
    command: "echo GOOS={{matrix}} "
    env:
      os: "{{matrix}}"
    matrix:
      - "$$BUILDKITE_PIPELINE_ID"
      - "Linux"
      - "Windows"
notify:
  - email: "stephanie@buildkite.com"
    if: build.state == "passed"
