steps:
  - label: "{{matrix}} build"
    command: "exit -1"
    env:
      os: "{{matrix}}"
    matrix:
      - "$$BUILDKITE_MESSAGE"
      - "Linux"
      - "Windows"

notify:
  - email: "stephanie@buildkite.com"
