steps:
  - label: "{{matrix}} build"
    command: "echo hi"
    env:
      os: "{{matrix}}"
    matrix:
      - "$$BUILDKITE_MESSAGE"
      - "Linux"
      - "Windows"
notify:
  - email: "stephanie@buildkite.com"
    if: build.state == "passed"
