steps:
- label: "Test Pipeline.yml"
  command: |
       if [ "$BUILDKITE_PULL_REQUEST_BASE_BRANCH" == "" ]; then
              echo "Exporting build variables"
              env:
               SHOULD_BUILD: "true"
              echo $SHOULD_BUILD
       fi
